# Generated by Django 2.1 on 2018-08-27 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0002_package_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='user_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Version'),
        ),
    ]
