# Generated by Django 2.1 on 2018-08-27 07:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(choices=[('PYPI_SDIST', 'sdist'), ('PYPI_WHEEL', 'bdist_wheel'), ('CONDA_LINUX64', 'linux-64'), ('CONDA_WIN64', 'win-64'), ('CONDA_NOARCH', 'noarch')], max_length=20)),
                ('build', models.CharField(max_length=20)),
                ('build_number', models.PositiveSmallIntegerField(default=int)),
                ('depends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('md5', models.CharField(max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField(default=int)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('filename', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_type', models.CharField(choices=[('MIT', 'MIT'), ('GPL', 'GPL'), ('BSD', 'BSD'), ('ALV', 'Apache v2'), ('PUBL', 'Public'), ('FREE', 'Other free'), ('PROPR', 'Proprietary'), ('NAN', 'Undefined')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('home_page', models.URLField(blank=True)),
                ('package_url', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('bugtrack_url', models.URLField(blank=True)),
                ('requires_dist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('last_serial', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('quality_check', models.CharField(choices=[('OFF', 'off'), ('QA_1', 'QA level 1'), ('QA_2', 'QA level 2'), ('PROD', 'production')], max_length=4)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'private'), ('TEAM', 'team'), ('PUBLIC', 'public')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('latest', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
        ),
    ]
